---
- hosts: all
  sudo: yes
  vars: 
    play_version: 2.2.1
    env_paths:
      - "/home/vagrant/playframework/play-{{ play_version }}"
    node_version: "0.10.12"
    node_prefix: "node-v${node_version}"
    node_tarball: "${node_prefix}.tar.gz"
    node_path: "/usr/local"


  tasks:
    # Update APT Caches and make sure base packages are installed
    - include: ./bootstrap/setup.yml

    # Install MongoDB
    - include: ./mongodb/setup.yml

    # Install Play
    - include: ./playframework/setup.yml

    # Install Nodejs
    - include: ./nodejs/setup.yml

